# frozen_string_literal: true

class AnsibleTowerClient::Api::V2::InventoryUpdate < AnsibleTowerClient::BaseModel
  schema do
    attribute :id, :integer
    attribute :type, :choice
    attribute :url, :string
    attribute :related, :object
    attribute :summary_fields, :object
    attribute :created, :datetime
    attribute :modified, :datetime
    attribute :name, :string
    attribute :description, :string
    attribute :unified_job_template, :field
    attribute :launch_type, :choice
    attribute :status, :choice
    attribute :failed, :field
    attribute :started, :datetime
    attribute :finished, :datetime
    attribute :elapsed, :decimal
    attribute :job_explanation, :string
    attribute :execution_node, :string
    attribute :source, :choice
    attribute :source_path, :string
    attribute :source_script, :field
    attribute :source_vars, :string
    attribute :credential, :integer
    attribute :source_regions, :string
    attribute :instance_filters, :string
    attribute :group_by, :string
    attribute :overwrite, :boolean
    attribute :overwrite_vars, :boolean
    attribute :timeout, :integer
    attribute :verbosity, :integer
    attribute :inventory, :field
    attribute :inventory_source, :field
    attribute :license_error, :boolean
    attribute :source_project_update, :field
    attribute :job_args, :string
    attribute :job_cwd, :string
    attribute :job_env, :field
    attribute :result_traceback, :string
    attribute :event_processing_finished, :boolean
    attribute :organization, :field
    attribute :kind, :choice
    attribute :cloud, :boolean
    attribute :host, :string
    attribute :username, :string
    attribute :password, :string
    attribute :security_token, :string
    attribute :project, :string
    attribute :domain, :string
    attribute :ssh_key_data, :string
    attribute :ssh_key_unlock, :string
    attribute :become_method, :choice
    attribute :become_username, :string
    attribute :become_password, :string
    attribute :vault_password, :string
    attribute :subscription, :string
    attribute :tenant, :string
    attribute :secret, :string
    attribute :client, :string
    attribute :authorize, :boolean
    attribute :authorize_password, :string
    attribute :event, :field
    attribute :counter, :integer
    attribute :event_display, :string
    attribute :event_data, :field
    attribute :changed, :field
    attribute :uuid, :string
    attribute :stdout, :string
    attribute :start_line, :integer
    attribute :end_line, :integer
    attribute :inventory_update, :field
    attribute :notification_template, :field
    attribute :error, :string
    attribute :notifications_sent, :integer
    attribute :notification_type, :choice
    attribute :recipients, :string
    attribute :subject, :string
  end
end
