# frozen_string_literal: true

class AnsibleTowerClient::Api::V2::Job < AnsibleTowerClient::BaseModel
  schema do
    attribute :id, :integer
    attribute :type, :choice
    attribute :url, :string
    attribute :related, :object
    attribute :summary_fields, :object
    attribute :created, :datetime
    attribute :modified, :datetime
    attribute :name, :string
    attribute :description, :string
    attribute :unified_job_template, :field
    attribute :launch_type, :choice
    attribute :status, :choice
    attribute :failed, :boolean
    attribute :started, :datetime
    attribute :finished, :datetime
    attribute :elapsed, :decimal
    attribute :job_explanation, :string
    attribute :execution_node, :string
    attribute :controller_node, :string
    attribute :job_type, :choice
    attribute :inventory, :field
    attribute :project, :string
    attribute :playbook, :string
    attribute :forks, :integer
    attribute :limit, :string
    attribute :verbosity, :integer
    attribute :extra_vars, :string
    attribute :job_tags, :string
    attribute :force_handlers, :boolean
    attribute :skip_tags, :string
    attribute :start_at_task, :string
    attribute :timeout, :integer
    attribute :use_fact_cache, :boolean
    attribute :job_template, :field
    attribute :passwords_needed_to_start, :field
    attribute :ask_diff_mode_on_launch, :boolean
    attribute :ask_variables_on_launch, :boolean
    attribute :ask_limit_on_launch, :boolean
    attribute :ask_tags_on_launch, :boolean
    attribute :ask_skip_tags_on_launch, :boolean
    attribute :ask_job_type_on_launch, :boolean
    attribute :ask_verbosity_on_launch, :boolean
    attribute :ask_inventory_on_launch, :boolean
    attribute :ask_credential_on_launch, :boolean
    attribute :allow_simultaneous, :boolean
    attribute :artifacts, :field
    attribute :scm_revision, :string
    attribute :instance_group, :field
    attribute :diff_mode, :boolean
    attribute :job_slice_number, :integer
    attribute :job_slice_count, :integer
    attribute :cloud_credential, :integer
    attribute :network_credential, :integer
    attribute :credential, :integer
    attribute :vault_credential, :integer
    attribute :job, :field
    attribute :host, :field
    attribute :host_name, :string
    attribute :changed, :integer
    attribute :dark, :integer
    attribute :failures, :integer
    attribute :ok, :integer
    attribute :processed, :integer
    attribute :skipped, :integer
    attribute :timestamp, :datetime
    attribute :operation, :choice
    attribute :changes, :field
    attribute :object1, :string
    attribute :object2, :string
    attribute :object_association, :field
    attribute :organization, :field
    attribute :kind, :choice
    attribute :cloud, :boolean
    attribute :username, :string
    attribute :password, :string
    attribute :security_token, :string
    attribute :domain, :string
    attribute :ssh_key_data, :string
    attribute :ssh_key_unlock, :string
    attribute :become_method, :choice
    attribute :become_username, :string
    attribute :become_password, :string
    attribute :vault_password, :string
    attribute :subscription, :string
    attribute :tenant, :string
    attribute :secret, :string
    attribute :client, :string
    attribute :authorize, :boolean
    attribute :authorize_password, :string
    attribute :event, :choice
    attribute :counter, :integer
    attribute :event_display, :string
    attribute :event_data, :field
    attribute :event_level, :integer
    attribute :uuid, :string
    attribute :parent_uuid, :string
    attribute :parent, :field
    attribute :play, :string
    attribute :task, :string
    attribute :role, :string
    attribute :stdout, :string
    attribute :start_line, :integer
    attribute :end_line, :integer
    attribute :notification_template, :field
    attribute :error, :string
    attribute :notifications_sent, :integer
    attribute :notification_type, :choice
    attribute :recipients, :string
    attribute :subject, :string
    attribute :can_start, :boolean, read-only
  end
end
