# frozen_string_literal: true

class AnsibleTowerClient::Api::V2::Organization < AnsibleTowerClient::BaseModel
  schema do
    attribute :id, :integer
    attribute :type, :choice
    attribute :url, :string
    attribute :related, :object
    attribute :summary_fields, :object
    attribute :created, :datetime
    attribute :modified, :datetime
    attribute :name, :string
    attribute :description, :string
    attribute :custom_virtualenv, :string
    attribute :username, :string
    attribute :first_name, :string
    attribute :last_name, :string
    attribute :email, :string
    attribute :is_superuser, :boolean
    attribute :is_system_auditor, :boolean
    attribute :ldap_dn, :string
    attribute :external_account, :field
    attribute :timestamp, :datetime
    attribute :operation, :choice
    attribute :changes, :field
    attribute :object1, :string
    attribute :object2, :string
    attribute :object_association, :field
    attribute :client_id, :string
    attribute :client_secret, :string
    attribute :client_type, :choice
    attribute :redirect_uris, :string
    attribute :authorization_grant_type, :choice
    attribute :skip_authorization, :boolean
    attribute :organization, :field
    attribute :kind, :choice
    attribute :cloud, :boolean
    attribute :host, :string
    attribute :password, :string
    attribute :security_token, :string
    attribute :project, :string
    attribute :domain, :string
    attribute :ssh_key_data, :string
    attribute :ssh_key_unlock, :string
    attribute :become_method, :choice
    attribute :become_username, :string
    attribute :become_password, :string
    attribute :vault_password, :string
    attribute :subscription, :string
    attribute :tenant, :string
    attribute :secret, :string
    attribute :client, :string
    attribute :authorize, :boolean
    attribute :authorize_password, :string
    attribute :capacity, :field
    attribute :committed_capacity, :field
    attribute :consumed_capacity, :field
    attribute :percent_capacity_remaining, :field
    attribute :jobs_running, :integer
    attribute :jobs_total, :integer
    attribute :instances, :field
    attribute :controller, :field
    attribute :policy_instance_percentage, :integer
    attribute :policy_instance_minimum, :integer
    attribute :policy_instance_list, :list
    attribute :host_filter, :string
    attribute :variables, :string
    attribute :has_active_failures, :boolean
    attribute :total_hosts, :integer
    attribute :hosts_with_active_failures, :integer
    attribute :total_groups, :integer
    attribute :groups_with_active_failures, :integer
    attribute :has_inventory_sources, :boolean
    attribute :total_inventory_sources, :integer
    attribute :inventory_sources_with_failures, :integer
    attribute :insights_credential, :field
    attribute :pending_deletion, :boolean
    attribute :notification_type, :choice
    attribute :notification_configuration, :field
    attribute :local_path, :string
    attribute :scm_type, :choice
    attribute :scm_url, :string
    attribute :scm_branch, :string
    attribute :scm_clean, :boolean
    attribute :scm_delete_on_update, :boolean
    attribute :credential, :field
    attribute :timeout, :integer
    attribute :last_job_run, :datetime
    attribute :last_job_failed, :boolean
    attribute :next_job_run, :datetime
    attribute :status, :choice
    attribute :scm_update_on_launch, :boolean
    attribute :scm_update_cache_timeout, :integer
    attribute :scm_revision, :string
    attribute :last_update_failed, :boolean
    attribute :last_updated, :datetime
    attribute :extra_vars, :string
    attribute :survey_enabled, :boolean
    attribute :allow_simultaneous, :boolean
    attribute :ask_variables_on_launch, :boolean
    attribute :inventory, :field
    attribute :ask_inventory_on_launch, :boolean
  end
end
