# frozen_string_literal: true

class AnsibleTowerClient::Api::V2::ProjectUpdate < AnsibleTowerClient::BaseModel
  schema do
    attribute :id, :integer
    attribute :type, :choice
    attribute :url, :string
    attribute :related, :object
    attribute :summary_fields, :object
    attribute :created, :datetime
    attribute :modified, :datetime
    attribute :name, :string
    attribute :description, :string
    attribute :unified_job_template, :field
    attribute :launch_type, :choice
    attribute :status, :choice
    attribute :failed, :boolean
    attribute :started, :datetime
    attribute :finished, :datetime
    attribute :elapsed, :decimal
    attribute :job_explanation, :string
    attribute :execution_node, :string
    attribute :local_path, :string
    attribute :scm_type, :choice
    attribute :scm_url, :string
    attribute :scm_branch, :string
    attribute :scm_clean, :boolean
    attribute :scm_delete_on_update, :boolean
    attribute :credential, :integer
    attribute :timeout, :integer
    attribute :project, :field
    attribute :job_type, :choice
    attribute :job_args, :string
    attribute :job_cwd, :string
    attribute :job_env, :field
    attribute :result_traceback, :string
    attribute :event_processing_finished, :boolean
    attribute :host_status_counts, :field
    attribute :event, :choice
    attribute :counter, :integer
    attribute :event_display, :string
    attribute :event_data, :field
    attribute :event_level, :integer
    attribute :changed, :boolean
    attribute :uuid, :string
    attribute :host_name, :field
    attribute :playbook, :string
    attribute :play, :string
    attribute :task, :string
    attribute :role, :string
    attribute :stdout, :field
    attribute :start_line, :integer
    attribute :end_line, :integer
    attribute :verbosity, :choice
    attribute :project_update, :field
    attribute :notification_template, :field
    attribute :error, :string
    attribute :notifications_sent, :integer
    attribute :notification_type, :choice
    attribute :recipients, :string
    attribute :subject, :string
    attribute :source, :choice
    attribute :source_path, :string
    attribute :source_script, :field
    attribute :source_vars, :string
    attribute :source_regions, :string
    attribute :instance_filters, :string
    attribute :group_by, :string
    attribute :overwrite, :boolean
    attribute :overwrite_vars, :boolean
    attribute :inventory, :field
    attribute :inventory_source, :field
    attribute :license_error, :boolean
    attribute :source_project_update, :field
  end
end
